name: move_metrics_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  firebase_auth: ^5.1.4
  firebase_core: ^3.3.0
  google_sign_in: ^6.2.0
  flutter:
    sdk: flutter
  get_it: ^7.7.0
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  cloud_firestore: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # State Management
  build_runner: ^2.3.3
  mobx_codegen: ^2.0.7

flutter:
  uses-material-design: true

  assets:
    - assets/
